package com.pbph.shoppingmall.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pbph.shoppingmall.model.dao.AddressDefault;
import com.pbph.shoppingmall.model.dao.BillDefault;
import com.pbph.shoppingmall.model.dao.CouponSearchRecord;
import com.pbph.shoppingmall.model.dao.SearchRecord;

import com.pbph.shoppingmall.greendao.AddressDefaultDao;
import com.pbph.shoppingmall.greendao.BillDefaultDao;
import com.pbph.shoppingmall.greendao.CouponSearchRecordDao;
import com.pbph.shoppingmall.greendao.SearchRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addressDefaultDaoConfig;
    private final DaoConfig billDefaultDaoConfig;
    private final DaoConfig couponSearchRecordDaoConfig;
    private final DaoConfig searchRecordDaoConfig;

    private final AddressDefaultDao addressDefaultDao;
    private final BillDefaultDao billDefaultDao;
    private final CouponSearchRecordDao couponSearchRecordDao;
    private final SearchRecordDao searchRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addressDefaultDaoConfig = daoConfigMap.get(AddressDefaultDao.class).clone();
        addressDefaultDaoConfig.initIdentityScope(type);

        billDefaultDaoConfig = daoConfigMap.get(BillDefaultDao.class).clone();
        billDefaultDaoConfig.initIdentityScope(type);

        couponSearchRecordDaoConfig = daoConfigMap.get(CouponSearchRecordDao.class).clone();
        couponSearchRecordDaoConfig.initIdentityScope(type);

        searchRecordDaoConfig = daoConfigMap.get(SearchRecordDao.class).clone();
        searchRecordDaoConfig.initIdentityScope(type);

        addressDefaultDao = new AddressDefaultDao(addressDefaultDaoConfig, this);
        billDefaultDao = new BillDefaultDao(billDefaultDaoConfig, this);
        couponSearchRecordDao = new CouponSearchRecordDao(couponSearchRecordDaoConfig, this);
        searchRecordDao = new SearchRecordDao(searchRecordDaoConfig, this);

        registerDao(AddressDefault.class, addressDefaultDao);
        registerDao(BillDefault.class, billDefaultDao);
        registerDao(CouponSearchRecord.class, couponSearchRecordDao);
        registerDao(SearchRecord.class, searchRecordDao);
    }
    
    public void clear() {
        addressDefaultDaoConfig.clearIdentityScope();
        billDefaultDaoConfig.clearIdentityScope();
        couponSearchRecordDaoConfig.clearIdentityScope();
        searchRecordDaoConfig.clearIdentityScope();
    }

    public AddressDefaultDao getAddressDefaultDao() {
        return addressDefaultDao;
    }

    public BillDefaultDao getBillDefaultDao() {
        return billDefaultDao;
    }

    public CouponSearchRecordDao getCouponSearchRecordDao() {
        return couponSearchRecordDao;
    }

    public SearchRecordDao getSearchRecordDao() {
        return searchRecordDao;
    }

}
